# Generated by Django 4.1.2 on 2022-10-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo_user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
