# Generated by Django 4.1.2 on 2022-10-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('correo', models.EmailField(max_length=200, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.tipo_user')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
